[package]
name = "digest"
version = "0.0.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
html2md = "0.2.14"
html2text = "0.12.6"
regex = "1.11.0"
reqwest = { version = "0.12.8", features = ["blocking"] }
rss = "2.0.9"
scraper = "0.20.0"
tiktoken-rs = "0.5.9"
