[package]
name = "digest"
version = "0.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
toml = "0"
chrono = "0"
html2text = "0"
regex = "1"
reqwest = { version = "0", features = ["blocking"] }
rss = "2"
serde = "1"
serde_derive = "1"
telegraph-rs = "0"
