# period = "week"
# date_from = "now" # "2021-01-01"
title = "Kirusha's Digest"
output_file = "example_digest.html"
feeds = [
    { name = "Scott Alexander", feed_url = "https://www.astralcodexten.com/feed", regex_filter = "(?i)(open thread|classfields)" },
    { name = "Robin Hanson", feed_url = "http://www.overcomingbias.com/feed", regex_filter = "$^" },
]
# summarization_prompt
# summarization_model
